/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        iris: {
          50:  'var(--iris-50)',
          100: 'var(--iris-100)',
          200: 'var(--iris-200)',
          300: 'var(--iris-300)',
          400: 'var(--iris-400)',
          500: 'var(--iris-500)',
          600: 'var(--iris-600)',
          700: 'var(--iris-700)',
          800: 'var(--iris-800)',
          900: 'var(--iris-900)',
          950: 'var(--iris-950)',
        },
        lilac: {
          50:  'var(--lilac-50)',
          100: 'var(--lilac-100)',
          200: 'var(--lilac-200)',
          300: 'var(--lilac-300)',
          400: 'var(--lilac-400)',
          500: 'var(--lilac-500)',
          600: 'var(--lilac-600)',
          700: 'var(--lilac-700)',
          800: 'var(--lilac-800)',
          900: 'var(--lilac-900)',
          950: 'var(--lilac-950)',
        },
        neutral: {
          0:   'var(--neutral-0)',
          50:  'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
        },
        brand: {
          primary:          'var(--brand-primary)',
          'primary-hover':  'var(--brand-primary-hover)',
          'primary-active': 'var(--brand-primary-active)',
          'primary-subtle': 'var(--brand-primary-subtle)',
          secondary:        'var(--brand-secondary)',
          'secondary-subtle': 'var(--brand-secondary-subtle)',
          'on-primary':     'var(--brand-on-primary)',
        },
        surface: {
          page:        'var(--surface-page)',
          card:        'var(--surface-card)',
          sunken:      'var(--surface-sunken)',
          'brand-wash': 'var(--surface-brand-wash)',
        },
        'border-color': {
          default: 'var(--border-default)',
          strong:  'var(--border-strong)',
          brand:   'var(--border-brand)',
        },
        'text-color': {
          primary:    'var(--text-primary)',
          secondary:  'var(--text-secondary)',
          muted:      'var(--text-muted)',
          'on-brand': 'var(--text-on-brand)',
          link:       'var(--text-link)',
        },
        success:         'var(--success)',
        'success-subtle': 'var(--success-subtle)',
        warning:         'var(--warning)',
        'warning-subtle': 'var(--warning-subtle)',
        error:           'var(--error)',
        'error-subtle':  'var(--error-subtle)',
        star: {
          gold:        'var(--star-gold)',
          'gold-deep': 'var(--star-gold-deep)',
          'gold-text': 'var(--star-gold-text)',
          'gold-subtle': 'var(--star-gold-subtle)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
